/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

/*
 * This file is autogenerated by kernel/tools/hardware_gen.py.
 */

#ifndef __PLAT_DEVICES_GEN_H
#define __PLAT_DEVICES_GEN_H
#include <linker.h>

#ifndef KDEV_BASE
#include <mode/hardware.h>
#endif

#define physBase 0x1000000

/* INTERRUPTS */
/* INTERRUPT_VGIC_MAINTENANCE generated from /soc/interrupt-controller@c4301000 */
#define INTERRUPT_VGIC_MAINTENANCE 25

/* INTERRUPT_VTIMER_EVENT generated from /timer */
#define INTERRUPT_VTIMER_EVENT 27

/* KERNEL_TIMER_IRQ generated from /timer */
#ifdef CONFIG_ARM_HYPERVISOR_SUPPORT
#define KERNEL_TIMER_IRQ 26
#else
#define KERNEL_TIMER_IRQ 27
#endif /* CONFIG_ARM_HYPERVISOR_SUPPORT */

/* KERNEL_UART_IRQ generated from /soc/bus@c8100000/serial@4c0 */
#define KERNEL_UART_IRQ 225

/* KERNEL DEVICES */
#define UART_PPTR (KDEV_BASE + 0x4c0)
#define GIC_V2_DISTRIBUTOR_PPTR (KDEV_BASE + 0x1000)
#define GIC_V2_CONTROLLER_PPTR (KDEV_BASE + 0x2000)
#define GIC_V2_VCPUCTRL_PPTR (KDEV_BASE + 0x3000)
#define WDOG_PPTR (KDEV_BASE + 0x48d0)

#ifndef __ASSEMBLER__
static const kernel_frame_t BOOT_RODATA kernel_devices[] = {
    /* /soc/bus@c8100000/serial@4c0 */
    {
        0xc8100000,
        /* contains UART_PPTR */
        KDEV_BASE + 0x0,
        true, /* armExecuteNever */
        true, /* userAvailable */
    },
    /* /soc/interrupt-controller@c4301000 */
    {
        0xc4301000,
        GIC_V2_DISTRIBUTOR_PPTR,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    /* /soc/interrupt-controller@c4301000 */
    {
        0xc4302000,
        GIC_V2_CONTROLLER_PPTR,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    #ifdef CONFIG_ARM_HYPERVISOR_SUPPORT
    /* /soc/interrupt-controller@c4301000 */
    {
        0xc4304000,
        GIC_V2_VCPUCTRL_PPTR,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    #endif /* CONFIG_ARM_HYPERVISOR_SUPPORT */
    /* /soc/bus@c1100000/watchdog@98d0 */
    {
        0xc1109000,
        /* contains WDOG_PPTR */
        KDEV_BASE + 0x4000,
        true, /* armExecuteNever */
        true, /* userAvailable */
    },
};

/* PHYSICAL MEMORY */
static const p_region_t BOOT_RODATA avail_p_regs[] = {
    { 0x1000000, 0x5000000 }, /* /memory@0 */
    { 0x5300000, 0x10000000 }, /* /memory@0 */
    { 0x10200000, 0x80000000 }, /* /memory@0 */
};

#endif /* !__ASSEMBLER__ */

#endif /* __PLAT_DEVICES_GEN_H */